/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Administrator
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        pnlCima = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        pnlTeste1 = new javax.swing.JPanel();
        lblTeste1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnTeste1 = new javax.swing.JButton();
        pnlTeste2 = new javax.swing.JPanel();
        lblTeste2 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnTeste2 = new javax.swing.JButton();
        pnlTeste3 = new javax.swing.JPanel();
        lblTeste3 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        btnTeste3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teste de Threads");
        setMaximumSize(new java.awt.Dimension(400, 450));
        setResizable(false);

        root.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        root.setPreferredSize(new java.awt.Dimension(400, 450));
        root.setLayout(new java.awt.BorderLayout());

        pnlCima.setBackground(new java.awt.Color(204, 204, 204));
        pnlCima.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlCima.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Teste de Threads");
        pnlCima.add(lblTitulo);

        root.add(pnlCima, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 40));

        pnlTeste1.setPreferredSize(new java.awt.Dimension(400, 70));
        pnlTeste1.setLayout(new javax.swing.BoxLayout(pnlTeste1, javax.swing.BoxLayout.Y_AXIS));

        lblTeste1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTeste1.setText("Teste Condição de Corrida e Sincronização:");
        pnlTeste1.add(lblTeste1);
        pnlTeste1.add(filler1);

        btnTeste1.setText("testar");
        btnTeste1.addActionListener(this::btnTeste1ActionPerformed);
        pnlTeste1.add(btnTeste1);

        pnlCentro.add(pnlTeste1);

        pnlTeste2.setPreferredSize(new java.awt.Dimension(400, 70));
        pnlTeste2.setLayout(new javax.swing.BoxLayout(pnlTeste2, javax.swing.BoxLayout.Y_AXIS));

        lblTeste2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTeste2.setText("Teste Travamentos no Swing (EDT)");
        pnlTeste2.add(lblTeste2);
        pnlTeste2.add(filler2);

        btnTeste2.setText("testar");
        btnTeste2.addActionListener(this::btnTeste2ActionPerformed);
        pnlTeste2.add(btnTeste2);

        pnlCentro.add(pnlTeste2);

        pnlTeste3.setPreferredSize(new java.awt.Dimension(400, 70));
        pnlTeste3.setLayout(new javax.swing.BoxLayout(pnlTeste3, javax.swing.BoxLayout.Y_AXIS));

        lblTeste3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTeste3.setText("Desafio Game Loop com TimerTask");
        pnlTeste3.add(lblTeste3);
        pnlTeste3.add(filler3);

        btnTeste3.setText("testar");
        btnTeste3.addActionListener(this::btnTeste3ActionPerformed);
        pnlTeste3.add(btnTeste3);

        pnlCentro.add(pnlTeste3);

        root.add(pnlCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTeste1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeste1ActionPerformed
        new Teste1().setVisible(true);
    }//GEN-LAST:event_btnTeste1ActionPerformed

    private void btnTeste2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeste2ActionPerformed
        new Teste2().setVisible(true);
    }//GEN-LAST:event_btnTeste2ActionPerformed

    private void btnTeste3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeste3ActionPerformed
        new Jogo().setVisible(true);
    }//GEN-LAST:event_btnTeste3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTeste1;
    private javax.swing.JButton btnTeste2;
    private javax.swing.JButton btnTeste3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel lblTeste1;
    private javax.swing.JLabel lblTeste2;
    private javax.swing.JLabel lblTeste3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlCima;
    private javax.swing.JPanel pnlTeste1;
    private javax.swing.JPanel pnlTeste2;
    private javax.swing.JPanel pnlTeste3;
    private javax.swing.JPanel root;
    // End of variables declaration//GEN-END:variables
}
