/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Administrator
 */
public class Teste2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Teste2.class.getName());

    /**
     * Creates new form Test2
     */
    public Teste2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        pnlEsquerdo = new javax.swing.JPanel();
        pnlEsquerdaCima = new javax.swing.JPanel();
        lblEsquerdaTItulo = new javax.swing.JLabel();
        pnlEsquerdaMeio = new javax.swing.JPanel();
        fillerEsquerda1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        pnlEsquerdaBotoes = new javax.swing.JPanel();
        btnEsquerdaBuscar = new javax.swing.JButton();
        btnEsquerdaSinal = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        pnlEsquerdaLog = new javax.swing.JPanel();
        scrEsquerda = new javax.swing.JScrollPane();
        txtEsquerda = new javax.swing.JTextArea();
        pnlDireito = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblDireitaTitulo = new javax.swing.JLabel();
        pnlDireitaMeio = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        pnlDireitaBotoes = new javax.swing.JPanel();
        btnDireitaBuscar = new javax.swing.JButton();
        btnDireitaSinal = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        pnlDireitaLog = new javax.swing.JPanel();
        scrDireita = new javax.swing.JScrollPane();
        txtDireita = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Background Thread");
        setMaximumSize(new java.awt.Dimension(500, 300));
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);

        root.setLayout(new java.awt.GridLayout(1, 2));

        pnlEsquerdo.setBackground(new java.awt.Color(51, 0, 255));
        pnlEsquerdo.setPreferredSize(new java.awt.Dimension(250, 300));
        pnlEsquerdo.setLayout(new java.awt.BorderLayout());

        pnlEsquerdaCima.setPreferredSize(new java.awt.Dimension(250, 40));
        pnlEsquerdaCima.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        lblEsquerdaTItulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEsquerdaTItulo.setText("Sem background Thread");
        pnlEsquerdaCima.add(lblEsquerdaTItulo);

        pnlEsquerdo.add(pnlEsquerdaCima, java.awt.BorderLayout.PAGE_START);

        pnlEsquerdaMeio.setLayout(new javax.swing.BoxLayout(pnlEsquerdaMeio, javax.swing.BoxLayout.Y_AXIS));
        pnlEsquerdaMeio.add(fillerEsquerda1);

        pnlEsquerdaBotoes.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlEsquerdaBotoes.setMinimumSize(new java.awt.Dimension(250, 30));
        pnlEsquerdaBotoes.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlEsquerdaBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));

        btnEsquerdaBuscar.setText("Buscar");
        btnEsquerdaBuscar.addActionListener(this::btnEsquerdaBuscarActionPerformed);
        pnlEsquerdaBotoes.add(btnEsquerdaBuscar);

        btnEsquerdaSinal.setText("Mandar sinal");
        btnEsquerdaSinal.addActionListener(this::btnEsquerdaSinalActionPerformed);
        pnlEsquerdaBotoes.add(btnEsquerdaSinal);

        pnlEsquerdaMeio.add(pnlEsquerdaBotoes);
        pnlEsquerdaMeio.add(filler1);

        pnlEsquerdaLog.setMaximumSize(new java.awt.Dimension(250, 100));
        pnlEsquerdaLog.setMinimumSize(new java.awt.Dimension(250, 100));
        pnlEsquerdaLog.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 0));

        txtEsquerda.setEditable(false);
        txtEsquerda.setColumns(20);
        txtEsquerda.setRows(5);
        txtEsquerda.setFocusable(false);
        scrEsquerda.setViewportView(txtEsquerda);

        pnlEsquerdaLog.add(scrEsquerda);

        pnlEsquerdaMeio.add(pnlEsquerdaLog);

        pnlEsquerdo.add(pnlEsquerdaMeio, java.awt.BorderLayout.CENTER);

        root.add(pnlEsquerdo);

        pnlDireito.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 40));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        lblDireitaTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDireitaTitulo.setText("Com background Thread");
        jPanel1.add(lblDireitaTitulo);

        pnlDireito.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnlDireitaMeio.setLayout(new javax.swing.BoxLayout(pnlDireitaMeio, javax.swing.BoxLayout.Y_AXIS));
        pnlDireitaMeio.add(filler2);

        pnlDireitaBotoes.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlDireitaBotoes.setMinimumSize(new java.awt.Dimension(250, 30));
        pnlDireitaBotoes.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlDireitaBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));

        btnDireitaBuscar.setText("Buscar");
        btnDireitaBuscar.addActionListener(this::btnDireitaBuscarActionPerformed);
        pnlDireitaBotoes.add(btnDireitaBuscar);

        btnDireitaSinal.setText("Mandar Sinal");
        btnDireitaSinal.addActionListener(this::btnDireitaSinalActionPerformed);
        pnlDireitaBotoes.add(btnDireitaSinal);

        pnlDireitaMeio.add(pnlDireitaBotoes);
        pnlDireitaMeio.add(filler3);

        pnlDireitaLog.setMaximumSize(new java.awt.Dimension(250, 100));
        pnlDireitaLog.setMinimumSize(new java.awt.Dimension(250, 100));
        pnlDireitaLog.setPreferredSize(new java.awt.Dimension(250, 100));
        pnlDireitaLog.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 0));

        txtDireita.setEditable(false);
        txtDireita.setColumns(20);
        txtDireita.setRows(5);
        txtDireita.setFocusable(false);
        scrDireita.setViewportView(txtDireita);

        pnlDireitaLog.add(scrDireita);

        pnlDireitaMeio.add(pnlDireitaLog);

        pnlDireito.add(pnlDireitaMeio, java.awt.BorderLayout.CENTER);

        root.add(pnlDireito);

        getContentPane().add(root, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsquerdaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsquerdaBuscarActionPerformed
        btnEsquerdaBuscar.setEnabled(false);
        txtEsquerda.append("Buscando...\n");
        try{Thread.sleep(5000);} catch(InterruptedException e) {}
        txtEsquerda.append("Busca encerrada!\n");
        btnEsquerdaBuscar.setEnabled(true);
    }//GEN-LAST:event_btnEsquerdaBuscarActionPerformed

    private void btnEsquerdaSinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsquerdaSinalActionPerformed
        txtEsquerda.append("\nSinal enviado\n");
    }//GEN-LAST:event_btnEsquerdaSinalActionPerformed

    private void btnDireitaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireitaBuscarActionPerformed
        Thread threadBusca = new Thread(new Runnable()
        {
           @Override
            public void run()
            {
                btnDireitaBuscar.setEnabled(false);
                txtDireita.append("Buscando...\n");
                try {Thread.sleep(5000);} catch(InterruptedException e) {}
                txtDireita.append("Busca encerrada!\n");
                btnDireitaBuscar.setEnabled(true);
            }
        });
        threadBusca.start();
    }//GEN-LAST:event_btnDireitaBuscarActionPerformed

    private void btnDireitaSinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireitaSinalActionPerformed
        txtDireita.append("\nSinal enviado!\n");
    }//GEN-LAST:event_btnDireitaSinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Teste2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDireitaBuscar;
    private javax.swing.JButton btnDireitaSinal;
    private javax.swing.JButton btnEsquerdaBuscar;
    private javax.swing.JButton btnEsquerdaSinal;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler fillerEsquerda1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDireitaTitulo;
    private javax.swing.JLabel lblEsquerdaTItulo;
    private javax.swing.JPanel pnlDireitaBotoes;
    private javax.swing.JPanel pnlDireitaLog;
    private javax.swing.JPanel pnlDireitaMeio;
    private javax.swing.JPanel pnlDireito;
    private javax.swing.JPanel pnlEsquerdaBotoes;
    private javax.swing.JPanel pnlEsquerdaCima;
    private javax.swing.JPanel pnlEsquerdaLog;
    private javax.swing.JPanel pnlEsquerdaMeio;
    private javax.swing.JPanel pnlEsquerdo;
    private javax.swing.JPanel root;
    private javax.swing.JScrollPane scrDireita;
    private javax.swing.JScrollPane scrEsquerda;
    private javax.swing.JTextArea txtDireita;
    private javax.swing.JTextArea txtEsquerda;
    // End of variables declaration//GEN-END:variables
}
