/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import condicao_corrida.RodarContagem;

/**
 *
 * @author Administrator
 */
public class Teste1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Teste1.class.getName());

    /**
     * Creates new form Teste1
     */
    public Teste1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JPanel();
        pnlEsquerda = new javax.swing.JPanel();
        pnlEsquerdaCima = new javax.swing.JPanel();
        pnlEsquerdaTitulo = new javax.swing.JLabel();
        pnlEsquerdaMeio = new javax.swing.JPanel();
        btnEsquerdaTestar = new javax.swing.JButton();
        txtEsquerdaResultado = new javax.swing.JTextField();
        pnlDireita = new javax.swing.JPanel();
        pnlDireitaCima = new javax.swing.JPanel();
        pnlDireitaTitulo = new javax.swing.JLabel();
        pnlDireitaCentro = new javax.swing.JPanel();
        btnDireitaTestar = new javax.swing.JButton();
        txtDireitaResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teste Condição de Corrida");
        setPreferredSize(new java.awt.Dimension(600, 150));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        root.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        root.setMinimumSize(new java.awt.Dimension(600, 100));
        root.setPreferredSize(new java.awt.Dimension(600, 100));
        root.setLayout(new java.awt.GridLayout(1, 2));

        pnlEsquerda.setPreferredSize(new java.awt.Dimension(300, 300));
        pnlEsquerda.setLayout(new java.awt.BorderLayout());

        pnlEsquerdaCima.setPreferredSize(new java.awt.Dimension(300, 40));
        pnlEsquerdaCima.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        pnlEsquerdaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlEsquerdaTitulo.setText("Sem Synchronized");
        pnlEsquerdaCima.add(pnlEsquerdaTitulo);

        pnlEsquerda.add(pnlEsquerdaCima, java.awt.BorderLayout.PAGE_START);

        pnlEsquerdaMeio.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        btnEsquerdaTestar.setText("Testar");
        btnEsquerdaTestar.addActionListener(this::btnEsquerdaTestarActionPerformed);
        pnlEsquerdaMeio.add(btnEsquerdaTestar);

        txtEsquerdaResultado.setEditable(false);
        txtEsquerdaResultado.setFocusable(false);
        txtEsquerdaResultado.setMinimumSize(new java.awt.Dimension(80, 26));
        txtEsquerdaResultado.setPreferredSize(new java.awt.Dimension(100, 26));
        txtEsquerdaResultado.addActionListener(this::txtEsquerdaResultadoActionPerformed);
        pnlEsquerdaMeio.add(txtEsquerdaResultado);

        pnlEsquerda.add(pnlEsquerdaMeio, java.awt.BorderLayout.CENTER);

        root.add(pnlEsquerda);

        pnlDireita.setBackground(new java.awt.Color(102, 102, 102));
        pnlDireita.setPreferredSize(new java.awt.Dimension(300, 300));
        pnlDireita.setLayout(new java.awt.BorderLayout());

        pnlDireitaCima.setPreferredSize(new java.awt.Dimension(297, 40));
        pnlDireitaCima.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        pnlDireitaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnlDireitaTitulo.setText("Com Synchronized");
        pnlDireitaCima.add(pnlDireitaTitulo);

        pnlDireita.add(pnlDireitaCima, java.awt.BorderLayout.PAGE_START);

        pnlDireitaCentro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        btnDireitaTestar.setText("Testar");
        btnDireitaTestar.addActionListener(this::btnDireitaTestarActionPerformed);
        pnlDireitaCentro.add(btnDireitaTestar);

        txtDireitaResultado.setEditable(false);
        txtDireitaResultado.setFocusable(false);
        txtDireitaResultado.setPreferredSize(new java.awt.Dimension(100, 26));
        pnlDireitaCentro.add(txtDireitaResultado);

        pnlDireita.add(pnlDireitaCentro, java.awt.BorderLayout.CENTER);

        root.add(pnlDireita);

        getContentPane().add(root);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEsquerdaResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEsquerdaResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEsquerdaResultadoActionPerformed

    private void btnEsquerdaTestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsquerdaTestarActionPerformed
        int resultadoEsquerdaInt=0;
        try
        {
           resultadoEsquerdaInt = RodarContagem.contarSem();
        } catch (InterruptedException ex) {}
        String resultadoEsquerda = Integer.toString(resultadoEsquerdaInt);
        txtEsquerdaResultado.setText(resultadoEsquerda);
    }//GEN-LAST:event_btnEsquerdaTestarActionPerformed

    private void btnDireitaTestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireitaTestarActionPerformed
        int resultadoDireitaInt=0;
        try 
        {
            resultadoDireitaInt = RodarContagem.contarCom();
        } catch (InterruptedException e) {}
        String resultadoDireita = Integer.toString(resultadoDireitaInt);
        txtDireitaResultado.setText(resultadoDireita);
    }//GEN-LAST:event_btnDireitaTestarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Teste1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDireitaTestar;
    private javax.swing.JButton btnEsquerdaTestar;
    private javax.swing.JPanel pnlDireita;
    private javax.swing.JPanel pnlDireitaCentro;
    private javax.swing.JPanel pnlDireitaCima;
    private javax.swing.JLabel pnlDireitaTitulo;
    private javax.swing.JPanel pnlEsquerda;
    private javax.swing.JPanel pnlEsquerdaCima;
    private javax.swing.JPanel pnlEsquerdaMeio;
    private javax.swing.JLabel pnlEsquerdaTitulo;
    private javax.swing.JPanel root;
    private javax.swing.JTextField txtDireitaResultado;
    private javax.swing.JTextField txtEsquerdaResultado;
    // End of variables declaration//GEN-END:variables
}
